#! /bin/bash

# Copyright (c) 2015, Matthew P. Grosvenor
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
# * Neither the name of the project, the name of copyright holder nor the names 
#   of its contributors may be used to endorse or promote products derived from
#   this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

ssh-add ~/id_rsa_qjump
timeout=120

for i in 1 10 25 50 75 90 100 250 500 750 900 1000 
#for i in 1
do 
    date
    window=$(expr 45 \* "$i")
    echo "Running for multiplier=$i and window=$window ..."

    ssh qjump@freestyle -C "sudo /home/qjump/qjump-expr-tools/memd-rate-expr/run_memcached_server $i $window" &
    server_pid=$!
    echo "Server pid=$server_pid ..."
    sleep 5 #Wait for the server to get going

    time ssh qjump@backstroke -C "sudo /home/qjump/qjump-expr-tools/memd-rate-expr/run_memcached_client $i $window $timeout" &
    client_pid=$!
    echo "Client pid=$client_pid ..."
    
    wait $client_pid
    ssh qjump@freestyle -C "sudo killall -9 memcached"
    sleep 1 
    kill -9 $server_pid
 
    date
    echo "======================================="
    echo
    echo

done
